
export const AGREGAR_PRODUCTO='AGREGAR_PRODUCTO';
export const AGREGAR_PRODUCTO_EXITO = 'AGREGAR_PRODUCTO_EXITO';
export const AGREGAR_PRODUCTO_ERROR = 'AGREGAR_PRODUCTO_ERROR';

export const COMENZAR_DESCARGA_PRODUCTOS= 'COMENZAR_DESCARGA_PRODUCTOS';
export const DESCARGA_PRODUCTOS_EXITO= 'DESCARGA_PRODUCTOS_EXITO';
export const DESCARGA_PRODUCTOS_ERROR= 'DESCARGA_PRODUCTOS_ERROR';

export const OBTENER_PRODUCTO_ELIMINAR= 'OBTENER_PRODUCTO_ELIMINAR';
export const PRODUCTO_ELIMINADO_EXITO= 'PRODUCTO_ELIMINADO_EXITO';
export const PRODUCTO_ELIMINADO_ERROR= 'PRODUCTO_ELIMINADO_ERROR';


//Lugares 
export const AGREGAR_LUGAR = 'AGREGAR_LUGAR';
export const AGREGAR_LUGAR_EXITO = 'AGREGAR_LUGAR_EXITO';
export const AGREGAR_LUGAR_ERROR = 'AGREGAR_LUGAR_ERROR';

export const COMENZAR_DESCARGA_LUGARES = 'COMENZAR_DESCARGA_LUGARES';
export const DESCARGA_LUGARES_EXITO = 'DESCARGA_LUGARES_EXITO';
export const DESCARGA_LUGARES_ERROR = 'DESCARGA_LUGARES_ERROR';

export const OBTENER_LUGARES_ELIMINAR = 'OBTENER_LUGARES_ELIMINAR';
export const LUGARES_ELIMINADO_EXITO = 'LUGARES_ELIMINADO_EXITO';
export const LUGARES_ELIMINADO_ERROR = 'LUGARES_ELIMINADO_ERROR';

//departamentos
export const AGREGAR_DEPARTAMENTO = 'AGREGAR_DEPARTAMENTO';
export const AGREGAR_DEPARTAMENTO_EXITO = 'AGREGAR_DEPARTAMENTO_EXITO';
export const AGREGAR_DEPARTAMENTO_ERROR = 'AGREGAR_DEPARTAMENTO_ERROR';

export const COMENZAR_DESCARGA_DEPARTAMENTOS = 'COMENZAR_DESCARGA_DEPARTAMENTOS';
export const DESCARGA_DEPARTAMENTOS_EXITO = 'DESCARGA_DEPARTAMENTOS_EXITO';
export const DESCARGA_DEPARTAMENTOS_ERROR = 'DESCARGA_DEPARTAMENTOS_ERROR';

export const OBTENER_DEPARTAMENTO_ELIMINAR = 'OBTENER_DEPARTAMENTO_ELIMINAR';
export const DEPARTAMENTO_ELIMINADO_EXITO = 'DEPARTAMENTO_ELIMINADO_EXITO';
export const DEPARTAMENTO_ELIMINADO_ERROR = 'DEPARTAMENTO_ELIMINADO_ERROR';


//usuarios
export const AGREGAR_USUARIO = 'AGREGAR_USUARIO';
export const AGREGAR_USUARIO_EXITO = 'AGREGAR_USUARIO_EXITO';
export const AGREGAR_USUARIO_ERROR = 'AGREGAR_USUARIO_ERROR';

export const COMENZAR_DESCARGA_USUARIOS = 'COMENZAR_DESCARGA_USUARIOS';
export const DESCARGA_USUARIOS_EXITO = 'DESCARGA_USUARIOS_EXITO';
export const DESCARGA_USUARIOS_ERROR = 'DESCARGA_USUARIOS_ERROR';

export const OBTENER_USUARIO_ELIMINAR = 'OBTENER_USUARIO_ELIMINAR';
export const USUARIO_ELIMINADO_EXITO = 'USUARIO_ELIMINADO_EXITO';
export const USUARIO_ELIMINADO_ERROR = 'USUARIO_ELIMINADO_ERROR';